Add slish to /etc/shells (used by dropbear) and some improvment

diff --git a/slish b/slish
--- a/slish
+++ b/slish
@@ -70,6 +70,11 @@ setup() {
 	done
 	# Activity log must be writable by users
 	touch ${activity} && chmod 0666 ${activity}
+	# Add /usr/bin/slish to /etc/shells (dropbear need it)
+	if ! fgrep -q '/usr/bin/slish' /etc/shells; then
+		echo "Adding /bin/slish to the list of valid shells..."
+		echo '/usr/bin/slish' >> /etc/shells
+	fi
 	echo "All done!"
 }
 
@@ -116,7 +121,7 @@ Subject: SliSH - Account created
 Content-Type: text/plain; charset=utf-8
 Content-Transfer-Encoding: 8bit
 
-Hi,
+Hi $name,
 
 Your custom SliTaz GNU/Linux SHell is ready to use! You can login with:
 
@@ -135,9 +140,18 @@ EOT
 
 # Add a new SliSH user
 add_user() {
+	#home="$root/./home/$user"
 	home="$root/home/$user"
 	shell="/usr/bin/slish"
 	
+	# Check values
+	if [ ! "$user" ] || [ ! "$name" ] || [ ! "$pass" ] || [ ! "$mail" ]; then
+		newline
+		echo "Missing option(s): --user= --name= --pass= --mail="
+		newline && exit 0
+	fi
+	
+	# Exit if user already exist
 	if grep -q ^${user}: /etc/passwd; then
 		newline
 		echo -n "User already exists: "; colorize 31 "$user"
@@ -146,7 +160,7 @@ add_user() {
 	fi
 	
 	newline
-	echo -n "$(boldify 'Creating user:') "; colorize 32 "$user"
+	echo -n "$(boldify 'Creating user:') "; colorize 34 "$user"
 	separator
 	echo -e "$pass\n$pass" | adduser -h "$home" -g "SliSH User" \
 		-s ${shell} ${user} >/dev/null
@@ -185,6 +199,7 @@ add_user() {
 
 # Add all users from the signup queue
 add_queued_user() {
+	echo "Checking: $queue"
 	for user in $(ls ${queue})
 	do
 		. ${queue}/${user}/account.conf
@@ -203,16 +218,16 @@ del_user() {
 		newline && exit 0
 	fi
 	newline
-	echo "$(boldify 'Deleting user:') $(colorize 32 "$user")"
+	echo "$(boldify 'Deleting user:') $(colorize 34 "$user")"
 	separator
 	echo -n "Removing user account from $(hostname) server"
 	deluser "$user"; status
 	sed -i "/^$user:/"d ${root}/etc/passwd
 	sed -i "/^$user:/"d ${root}/etc/group
 	echo -n "Removing all files in : $home"
-	rm -rf ${home} ; status
+	rm -rf ${home}; status
 	echo -n "Removing user config  : $people/$user"
-	rm -rf "${people}/${user}" ; status
+	rm -rf "${people}/${user}"; status
 	separator && newline
 }
 
@@ -300,7 +315,7 @@ case "$1" in
 	adduser)
 		# We can adduser from cmdline or from the signup queue
 		check_root
-		if [ "$from-queu" ]; then
+		if [ "$queued" ]; then
 			add_queued_user
 		else
 			add_user
@@ -331,7 +346,7 @@ case "$1" in
 			. ${people}/"$USER"/account.conf
 			log "Chrooting user: $USER"
 			ulimit $(echo "$ULIMIT")
-			exec chroot ${root} /bin/slish.sh "$@"
+			exec /usr/sbin/chroot ${root} /bin/slish.sh "$@"
 		else
 			usage
 		fi ;;
